### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by FlipFlop17** [theron-wang/VS2022-Editor-Support-for-Tailwind-CSS#13]
Hi, 

Good work on the extension, VS could use all the help it can get with tailwind intelissense.
I'd like to suggest maybe some more comprehensive guide on the installation steps. 
It is not mentioned anywhere about adding the `<link>` in the `<head>` section and the @tailwind directives inside input.css file
Also maybe numbering the installation steps for the newcomers.

all the best

**Comment by theron-wang** [comment]
Yeah, I think this would be useful for new users. I'll write up a guide. Thank you for suggesting!

**Comment by theron-wang** [comment]
Getting started guide updated here: https://github.com/theron-wang/VS2022-Editor-Support-for-Tailwind-CSS/blob/main/Getting-Started.md.

As for adding css files in `<head>`, I chose not to include that (rather, I linked the official Tailwind docs instead), since that pertains more to the actual framework rather than the extension.

Again, thanks for suggesting this!
