### ISSUE TITLE
Sometimes it doesn't compile

### ISSUE THREAD

**Issue by wdridoy11** [theron-wang/VS2022-Editor-Support-for-Tailwind-CSS#33]
My tailwind CSS code not work sometime. My app-tailwind.css doesn't compile sometime.  It doesn't compile all file something. The extension not working. 

It is my tailwind.extension.json file code.
{
  "ConfigurationFile": "tailwind.config.js",
  "InputCssFile": "wwwroot\\Tailwind\\tailwind-input.css",
  "OutputCssFile": "wwwroot\\Tailwind\\app-tailwind.css"
}

It is my tailwind.config.js file code,
const defaultTheme = require('tailwindcss/defaultTheme')

module.exports = {
    content: ["..//*.{html,cshtml,razor,js}"],
    darkMode: 'class',
    theme: {
        extend: {
        },
    },
    plugins: [],
}
[tailwind.zip](https://github.com/theron-wang/VS2022-Editor-Support-for-Tailwind-CSS/files/14025244/tailwind.zip)

**Comment by theron-wang** [comment]
The file should compile each time you build the project or manually start the build process. If your files aren’t compiling, I believe it might be an issue with your configuration file, rather than the extension (`content: ["../**/*.{html,cshtml,razor,js}"]` rather than `content: ["..//*.{html,cshtml,razor,js}"]`). Just to confirm, are there any Tailwind errors outputted in the Build or Extensions output panes?

Thanks!
