### ISSUE TITLE
Classes from extensions don't have tooltip on hover

### ISSUE THREAD

**Issue by v36u** [theron-wang/VS2022-Editor-Support-for-Tailwind-CSS#66]
_Issue opened after upgrading to 1.5.2. (P.S.: Intellisense now works like a charm for 3rd party extensions! Thanks!)_

<details>
<summary>Working example with standard class</summary>

![image](https://github.com/user-attachments/assets/c8f9e04a-0c64-4098-abca-c92e9f64df68)
</details>

<details>
<summary>Custom class defined in the `extend` section of `tailwind.config.js`</summary>

Definition:
```
module.exports = {
  ...
  theme: {
    ...
    extend: {
      colors: {
        'primary': '#6e25d0',
      },
      ...
    },
  },
  ...
};
```

Screenshot:
![image](https://github.com/user-attachments/assets/02038553-82de-4528-a645-7fa1a849cc02)
(on hover it does not display anything)
</details>

<details>
<summary>Custom class from 3rd party extension</summary>

Definition:
```
module.exports = {
  ...
  plugins: [
    require('tailwindcss-3d'),
  ],
};
```

Screenshot:
![image](https://github.com/user-attachments/assets/548d8205-d55f-4ae7-8456-f4e350722802)
(on hover it does not display anything)
</details>

**Edit:** This also happens for classes with custom values such as `min-w-[258px]`

**Comment by theron-wang** [comment]
> Custom class defined in the `extend` section of `tailwind.config.js`

I used the segment you provided and the tooltip does seem to appear on hover for `from-primary`. If possible, could you send a larger example than the current one? I suspect that the parser is working incorrectly, possibly due to a JS pattern that I haven't tested before.

As for the tooltips for plugins and custom values, it should be added in 1.5.3. One caveat for classes with custom values though: it currently only works for classes using spacing or colors (i.e. `p-[20px]` or `bg-[#fff]` but not `rotate-[45deg]`), but I may revisit this in the future.

Thank you!

**Comment by v36u** [comment]
> If possible, could you send a larger example than the current one?

No longer a problem! Works like a charm with v1.5.3! Thank you very much!

![image](https://github.com/user-attachments/assets/d3743ca9-9d69-4bad-83ca-b97a879f34d4)

![image](https://github.com/user-attachments/assets/ba81f358-ace7-49be-8236-674e6eeda4f8)

> As for the tooltips for plugins and custom values, it should be added in 1.5.3.

Yep!

![image](https://github.com/user-attachments/assets/749c4251-31af-40e9-bc29-23c62db324fe)

**Comment by theron-wang** [comment]
Thanks! Tooltips should now work for all classes :) (1.5.4)

**Comment by v36u** [comment]
Yes. Tooltips now work for all classes! Thank you!
