### ISSUE TITLE
[Feature Request] Add css snippet inline or as a tooltip to autocomplete list

### ISSUE THREAD

**Issue by gpshonik** [theron-wang/VS2022-Editor-Support-for-Tailwind-CSS#7]
Thank you for this extension, it was very much needed for VS 2022.

Would it be possible to add the actual css for the official tailwind classes to the auto complete as follows?

<img width="239" alt="image" src="https://github.com/theron-wang/VS2022-Editor-Support-for-Tailwind-CSS/assets/1524361/a5514180-0acc-4d7e-9080-e75495695bd9">

This is an example from the official tailwind extension for VS Code.

Thank you!

**Comment by theron-wang** [comment]
This is definitely a needed feature. I added it into the extension, but I did change make the CSS show up as a description instead of a suffix (as shown in this gif):

![IntelliSense-Demo-1](https://github.com/theron-wang/VS2022-Editor-Support-for-Tailwind-CSS/assets/65189291/8da1be72-0918-447b-aafb-5ecac09e97f9)

Thanks for the suggestion!

**Comment by gpshonik** [comment]
Thank you very much for implementing this so quickly! After updating the
extension to the latest version, I saw the auto-complete trigger briefly
but then an Object reference not set to an instance of an object dialog
popped up (and pops up on each subsequent key press)

[image: image.png]

Happy to provide any other details if needed.

**Comment by gpshonik** [comment]
Sorry about that, not sure what happened with the image.

<img width="350" alt="image" src="https://github.com/theron-wang/VS2022-Editor-Support-for-Tailwind-CSS/assets/1524361/aa72a967-c2ba-4541-8eea-a664f78400a5">
