### ISSUE TITLE
Issue with building TW "Build stopped (1 processes left)"

### ISSUE THREAD

**Issue by DannyPhoenix** [theron-wang/VS2022-Editor-Support-for-Tailwind-CSS#78]
I'm not sure what other information I can share to help.

![image](https://github.com/user-attachments/assets/a1e88229-c3f2-44b6-ba1b-2d76b1c03ec2)

But here is what I have tried so far:
1. Uninstalled and reinstalled extension
2. Updated to the latest version (I think I was on 1.5.xx before)
3. Unmapped all of the config files (input, output, config)
4. Clean / Rebuild project

Project is a Blazor app.

![image](https://github.com/user-attachments/assets/3e8a41b7-b552-4adc-b950-b4c30fa10bbe)

**Comment by theron-wang** [comment]
This is actually working as intended: `Manual` builds once instead of running with `--watch`. In 1.6.3, I added a `ManualJIT` build option (like `Manual`, but it runs until manually stopped: `--watch`), which should be what you're looking for. I apologize for the confusing descriptions in the `Build type` setting; I've also made them clearer in 1.6.3. Thank you :)!
