### ISSUE TITLE
AlpineJS class object syntax breaks when being sorted

### ISSUE THREAD

**Issue by skttl** [theron-wang/VS2022-Editor-Support-for-Tailwind-CSS#86]
When I assign classes with [Alpine.js' class object syntax](https://alpinejs.dev/directives/bind#class-object-syntax) the extension has suddenly started to corrupt this syntax. I have been using the extension for years, and Alpine.js for years, so I have no idea why it suddenly started doing this.

I tried disabling the extension, and then the attribute stays as it is, when saving the file, so I'm pretty certain that this is a bug in this extension.

Can we make some kind of exception, so the extension doesn't sort classes between { and }?

![devenv_80IIm0qIy3](https://github.com/user-attachments/assets/5799c1a4-9bba-407d-bf6e-98f7cf93df90)

**Comment by skttl** [comment]
It might be as simple as adding `\s` (to require a whitespace character before `class`) in the start of these regexes: https://github.com/theron-wang/VS2022-Editor-Support-for-Tailwind-CSS/blob/ff2172486b1368e64ae97e3048d34b891c9ce8f5/src/Helpers/ClassRegexHelper.cs#L12

But of course it would be nice if it could sort the classes (and offer intellisense) inside the object too :)

**Comment by skttl** [comment]
Adding `\s[cC]lass\s*=\s*(['""])\s*(?<content>(?:\n.|(?!\1).)*)?\s*(\1|$)` to my custom regex seems to fix it.

Can it be added in tailwind.extension.js too, to make it easier to enforce on a project basis?

**Comment by theron-wang** [comment]
Thanks. I will either add a safeguard to stop class sorting when apostrophes are present, or I will re-add direct support for Alpine, as you suggested, in the future.

> It might be as simple as adding \s (to require a whitespace character before class) in the start of these regexes:

Unfortunately, I can’t do this because the extension has historically supported IntelliSense in razor components, which can have classes in variables and custom attributes. 

Regarding custom regexes in tailwind.extension.json files, I do believe this is the right way to go forward.

Thank you for your help and your patience! I apologize for my oversight.

**Comment by theron-wang** [comment]
@skttl This should be fixed in 1.7.1. I've also included your suggestion for project-based custom regexes (see more details [here](https://github.com/theron-wang/VS2022-Editor-Support-for-Tailwind-CSS/blob/main/Getting-Started.md#customizing-your-tailwindextensionjson-file)). Please let me know if you run into any further issues!

**Comment by skttl** [comment]
That is amazing - thanks!
